# Project information
site_name: Clinical Medicine Notes
site_description: Clinical Medicine Notes
site_author: Jingzhi An
site_url: http://localhost:8000

# Repository
repo_name: jingzhian/mkdocs-md-notes
repo_url: https://github.com/jingzhian/mkdocs-md-notes

# Copyright
copyright: Copyright &copy; 2020 Jingzhi An

# Configuration
theme:
  name: material
  language: en
  palette:
    primary: teal
    accent: teal
  font:
    text: Roboto
    code: Roboto Mono
  features:
    # - instant
    - tabs
  icon:
    logo: material/library
    repo: fontawesome/brands/github-square    

# Extras
extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/jingzhian
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/drdrjzan
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/in/jingzhi-an-281a9315

# Google Analytics
# google_analytics:
#   - UA-XXXXXXXX-X
#   - auto

plugins:
  - search:
      prebuild_index: true
  - git-revision-date-localized
  - awesome-pages
  
# Extensions
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
  - footnotes
  - meta
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:pymdownx.emoji.twemoji
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tabbed
  - pymdownx.tilde


extra_javascript:
  - javascripts/extra.js
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

extra_css: 
  - stylesheets/numbered-headings.css


nav:
  - Home: index.md
  - Exam Info: exam-info.md
  - Healthcare System: healthcare-system.md
  - Basics of Anatomy, Physiology & Pathology: biomed-sciences.md
  - Foundation of Clinical Medicine: clinic-foundation.md
  - Bedside Etiquette: encounter.md
  - Common presentations: approach.md
  - emergency.md
  - neurology.md
  - endocrinology.md
  - cardiovascular.md
  - pulmonology.md
  - gi.md
  - urorenal.md
  - obstetrics.md
  - hematology.md
  - oncology.md
  - msk.md
  - rheumatology.md
  - psychiatry.md
  - frontiers.md
  - palliative.md
  - UWorld Complete:
    - dermatology.md
    - psychiatry.md
    - ophthalmology.md
  - Temporary notes: 
    - temp-notes.md
  - Unorganized:
    - ENT.md
    - anesthesiology.md
    - fammed.md
    - genetic-medicine.md
    - id.md
    - pharmaco.md
    - presentation.md
    - reproductive.md
    - respiratory.md
    - review-peds.md
    - surgery.md  
  #- Completed:

    